### ISSUE TITLE
InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by andrewlock** [tonyredondo/timeitsharp#49]
Spotted in a profiler execution benchmarks run: https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=147975&view=logs&j=4a07b9ac-0f22-5a85-82e2-358a7042f665&t=adc732be-4c63-519a-4f88-26890123bcd6

```
Unhandled exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.MinFloat[T](IEnumerable`1 source)
   at TimeIt.ConsoleExporter.Export(IEnumerable`1 results) in /_/src/TimeIt/ConsoleExporter.cs:line 142
   at Program.<>c.<<<Main>$>b__0_0>d.MoveNext() in /_/src/TimeIt/Program.cs:line 101
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

```

**Comment by tonyredondo** [comment]
Which version is the profiler using? because `src/TimeIt/Program.cs` is a really old path structure...
